import { defineConfig } from "oxfmt";

export const base = defineConfig({
  arrowParens: "always",
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: "auto",
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "css",
  ignorePatterns: ["node_modules/"],
  insertFinalNewline: true,
  jsdoc: {
    addDefaultToDescription: true,
    bracketSpacing: true,
    capitalizeDescriptions: true,
    commentLineStrategy: "singleLine",
    descriptionTag: false,
    descriptionWithDot: false,
    keepUnparsableExampleIndent: false,
    lineWrappingStyle: "greedy",
    preferCodeFences: false,
    separateReturnsFromParam: false,
    separateTagGroups: false,
  },
  jsxSingleQuote: false,
  objectWrap: "preserve",
  overrides: [],
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  semi: true,
  singleAttributePerLine: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
});
