auditLevel: "high"
blockExoticSubdeps: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeStrict: true
nodeLinker: "isolated"
preferFrozenLockfile: true
preferOffline: false
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: true
trustPolicy: "no-downgrade"

packages:
  - "packages/*"

catalog:
  "@changesets/cli": "2.31.0"
  "typescript": "5.9.3"
